replicaCount: 3

image:
  repository: dsohar/star-trek-quiz
  pullPolicy: Always
  tag: "latest"

app:
  port: 5001
  questionsFile: "/app/star-trek-quiz.json"
  leaderboardFile: "/app/leaderboard.json"

secret:
  secretKey: "replace-me" # real key should not be pushed to git

service:
  type: ClusterIP
  port: 5001

ingress:
  className: nginx
  # host: star-trek-quiz.192.168.49.2.nip.io
  ip: 192.168.49.2
  pathType: Prefix

