apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-config
  labels:
    {{- include "star-trek-quiz.labels" . | nindent 4 }}

data:
  questionsFile: {{ .Values.app.questionsFile | quote }}
  leaderboardFile: {{ .Values.app.leaderboardFile | quote }}
  port: {{ .Values.app.port | quote }}