apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
  labels:
    {{- include "star-trek-quiz.labels" . | nindent 4 }}

type: Opaque

stringData:
  secretKey: {{ .Values.secret.secretKey | quote }}